name: Endor SARIF Scan and Upload

on:
  workflow_dispatch: # Manual trigger
  push:              # Automatically run on push to any branch

permissions:
  contents: read
  security-events: write   # Required to upload SARIF to GitHub

jobs:
  sarif-upload:
    runs-on: macos-latest   # MacOS runner for ARM64

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # Step 2: Debug Git (optional, remove after workflow works)
      - name: Debug Git
        run: |
          echo "Current directory: $PWD"
          git status
          git branch
          ls -la

      # Step 3: Install Endor Labs CLI for MacOS ARM64
      - name: Install Endor Labs CLI
        run: |
          # Download latest CLI
          curl -L https://api.endorlabs.com/download/latest/endorctl_macos_arm64 -o endorctl

          # Verify checksum
          echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_macos_arm64)  endorctl" | shasum -a 256 -c

          # Make it executable
          chmod +x ./endorctl

          # Make endorctl available in PATH
          export PATH="$PWD:$PATH"

      # Step 4: Run Endor scan and generate SARIF
      - name: Run Endor scan
        run: ./endorctl scan --sarif-file findings.sarif

      # Step 5: Upload SARIF results to GitHub
      - name: Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: findings.sarif
